FROM pmdumuid/postgres:9.6.24-bullseye

RUN apt-get update \
    && apt-get -y install python2 ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py > /tmp/get-pip.py \
    && python2 /tmp/get-pip.py \
    && rm -rf /tmp/get-pip.py

RUN apt-get update \
    && apt-get -y install gcc python2-dev libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && python2 -m pip install psycopg2 \
    && apt-get -y --purge autoremove gcc python2-dev libpq-dev
